name: doc-archive

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-docdb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d
    command: postgres -c shared_preload_libraries=vector
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d docdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - doc-net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped
    networks:
      - doc-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    networks:
      - doc-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./deploy/infra/cors-config.json:/cors-config.json
    entrypoint: >
      /bin/sh -c "
        mc alias set myminio http://minio:9000 ${MINIO_USER:-minioadmin} ${MINIO_PASSWORD:-minioadmin};
        mc mb myminio/${MINIO_BUCKET:-pdf-documents} --ignore-existing;
        echo 'Bucket ${MINIO_BUCKET:-pdf-documents} created successfully';

        mc cors set myminio/$$MINIO_BUCKET /cors-config.json;
        echo 'CORS policy applied successfully.';
        exit 0;
      "

  embedder:
    build: ./embedder
    container_name: embedder
    environment:
      EMBED_MODEL_NAME: ${EMBED_MODEL:-all-MiniLM-L6-v2}
      RERANK_MODEL_NAME: ${RERANK_MODEL:-cross-encoder/ms-marco-MiniLM-L-6-v2}
      READER_MODEL_NAME: ${READER_MODEL:-distilbert-base-cased-distilled-squad}
      MAX_TEXT_LENGTH: 5000
      HF_TOKEN: ${HF_TOKEN:-}
      HF_HOME: /cache/huggingface  # for cache
    ports:
      - "5001:5000"
    volumes:
      - hf_cache:/cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - doc-net

  api:
    build: ./server
    container_name: api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-pass}@postgres:5432/${POSTGRES_DB:-docdb}?sslmode=disable
      REDIS_URL: redis:6379
      MINIO_URL: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_USER:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_PASSWORD:-minioadmin}
      MINIO_BUCKET: ${MINIO_BUCKET:-pdf-documents}
      EMBEDDER_URL: http://embedder:5000
      RERANKER_URL: http://embedder:5000
      READER_URL: http://embedder:5000
      PORT: 8080
      ENV: development
      SECRET_KEY: ${SECRET_KEY:-your-strong-secret-key}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      embedder:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - doc-net

  webui:
    build: ./webui
    container_name: webui
    environment:
      GO_API_BASE_URL: http://api:8080
      SECRET_KEY: ${SECRET_KEY:-your-strong-secret-key}
    ports:
      - "5005:5000"
    depends_on:
      api:
        condition: service_started
    networks:
      - doc-net


volumes:
  pgdata:
  redisdata:
  miniodata:
  hf_cache:

networks:
  doc-net:
    driver: bridge

